### ISSUE TITLE
你好，win_output_debug.h 这个文件是哪的?

### ISSUE THREAD

**Issue by uudiin** [jeppeter/nsduilib#1]
如题，编译不通过
VS2013

#include <win_output_debug.h>
#include <win_uniansi.h>
#include <win_window.h>
这几个都找不到

**Comment by jeppeter** [comment]
你这里最大的可能性是没有 git这个程序，在windows下面，
我这里还要依赖于一个git库的，在生成的时候，会从github上下载的。

2017-06-09 11:21 GMT+08:00 uudiin <notifications@github.com>:

**Comment by uudiin** [comment]
代码就是git clone的，没有submodule，也没有README说明

**Comment by jeppeter** [comment]
你的运行环境是否能够运行git 也就是在你的cmd下面如果输入 git version会输出什么。我在readme.txt中已经说明了。要什么程序
我自己这里是正常的。可以编译的。你这里要下载https://github.com/jeppeter/clibs 这里的代码库到这个的目录下面就可以了。

2017-06-12 10:43 GMT+08:00 uudiin <notifications@github.com>:

**Comment by uudiin** [comment]
就是git bash环境，我直接下clibs看看吧
那一堆VB的代码看不懂，确实是不敢运行啊，要是shell脚本还可以

**Comment by zhww1** [comment]
你好，我环境配置是VS2013 打开工程有两个项目一个duilib和 nsduilib，我电脑安装有git版本是2.20.1，nsis版本是3.05 ，运行脚本也下载了clibs，配置路径之后编译Dulib 库没有问题，在编译nsduilib的时候提示缺少 output_debug.lib 库对于这个库是怎么编译出来的？？，我们这个工程支持VS2013吗？我首次打开提示 。。

**Comment by jeppeter** [comment]
支持VS2013，但你所使用的方法是makeall.bat的调用就可以了。这个就直接编译出你要的文件了。

**Comment by zhww1** [comment]
> 支持VS2013，但你所使用的方法是makeall.bat的调用就可以了。这个就直接编译出你要的文件了。

我直接运行makeall.bat没有反应，运行makedll.bat在当前目录（与makedll.bat 同一目录）下载了clis。
最后使用VS配置了一下路径 单独编译了Duilib  和nsduilib这两个工程提示缺少连接库 out_put_debug.lib  我最后直接将下载clis目录下的winlib文件给编译了一下（生成静态库，然后在编译nsduilib这个工程就不报错误了。生成了nsduilib.dll    ...不知道我不使用.bat 脚本这种单独在VS下面编译每一个工程是否可以。。。因为我发现最后叶生成了nsduilib.dll这个库了。

**Comment by jeppeter** [comment]
现在的编译，已经使用nmake的语法，所以，与VS的版本关系不大，你这里说的，很有可能是你没有安装nsis的程序，或者这个程序所在的目录没有在PATH中。
